title: Github Pages with Jekyll
author: Juan Carlos Lopez
email: jclopezdev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learn how to create a site or blog from your GitHub repositories 
  with GitHub Pages and Jekyll.

# social links
twitter_username: https://twitter.com/jcarloslopezl
github_username:  https://github.com/jclopezdev

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
